LB-Test:
  ports:
  - ${check_port}:80
  labels:
    io.rancher.scheduler.affinity:host_label: AlanTestLB=True
  tty: true
  image: rancher/load-balancer-service
  links:
  - WebServer:WebServer
  stdin_open: true
WebServer:
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label: AlanTestLB=True
  environment:
    KEEP_VIP: "${virtual_ip}"
  tty: true
  image: httpd
  stdin_open: true
Keepalived:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: AlanTestLB=True
  environment:
    VIRTUAL_IP: "${virtual_ip}"
    CHECK_PORT: "${check_port}"
    VRID: 150
    INTERFACE: "${network_interface}"
    NETMASK_BIT: "${netmask_bit}"
  tty: true
  image: alanpeng/rancher-keepalived
  stdin_open: true
  net: host
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST

