.catalog:
  name: "Keepalived for Rancher"
  version: 0.1
  description: |
    Keepalived for Rancher HA-Proxy Loadbalancer
  questions:
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "Virtual Floating IP Address"
      description: "Virtual IP address given to the HA-Proxy Cluster"
    - variable: "pxc_sst_password"
      type: string
      required: true
      label: "listening port"
      description: "The listening port of the HA-Proxy loadbalancer"   
      default: "80"
